site_name: 稻草人日记
site_url: https://ch3nwe1.github.io/scaresrow

nav:
    - 主页: index.md
    - 程序: 
      - Python: 
        - 基础教程: 
            - 注释: python/基础教程/注释.md
            - 元组与列表: python/基础教程/元组与列表.md
            - 字符串: python/基础教程/字符串.md
            - 字典: python/基础教程/字典.md
            - 条件控制和循环结构: python/基础教程/条件控制与循环结构.md
            - 函数:  python/基础教程/函数.md
      - Java: 
        - 字符串: java/String.md
        - ReentrantLock: java/JUC/ReentrantLock.md
        - Queue: java/JUC/Queue.md
        - Blocking: java/JUC/BlockingQueue.md
        - PriorityQueue: java/Collection/PriorityQueue.md 
        - ArrayBlockingQueue: java/JUC/ArrayBlockingQueue.md
        - DelayQueue: java/JUC/DelayQueue.md
        - PriorityBlockingQueue: java/JUC/PriorityBlockingQueue.md
        - FutureTask: java/JUC/FutureTask.md
        - ThreadPoolExecutor: java/JUC/ThreadPoolExecutor.md  
        - jaxws:
            - jaxws-2.3: java/jaxws/jaxws-2.3.pdf
            - release-documentation: java/jaxws/jax-ws-release-documentation.pdf
            - jaxb: java/jaxws/JAXB-2.3-spec.pdf
            - jaxrs: java/jaxws/jaxrs-2_1-final-spec.pdf
            - jaxws-2.0: java/jaxws/jaxws-2_0-fr-spec.pdf
            - jsr: java/jaxws/JSR181-2.1-MR.pdf
            - web service: java/jaxws/Web Service Definition Language (WSDL).pdf
      - Redis:
        - redis command: Redis/redis command.md
        - redis-replication: Redis/redis-replication.md
      - VIM:
        - VIM: VIM/vim.md
      - XML:
        - xml-structures: xml/W3C XML Schema Definition Language (XSD) 1.1 Part 1_ Structures.pdf
        - xml-datatypes: xml/W3C XML Schema Definition Language (XSD) 1.1 Part 2_ Datatypes.pdf
    - 关于: about.md


theme: mkdocs
